config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {  registrations: "registrations" }
  resources :leads
  resources :panel

  root to: 'leads#index'

end

app/models/baby.rb
class Baby < ActiveRecord::Base
  belongs_to :family
end

app/models/family.rb
class Family < ActiveRecord::Base
  belongs_to :user

  has_one :mother
  has_one :father
  has_many :babies
end

app/models/father.rb
class Father < ActiveRecord::Base
  belongs_to :family
end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/models/mother.rb
class Mother < ActiveRecord::Base
  belongs_to :family
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :family
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    return panel_index_path
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  layout 'site'

  def index
    @lead = Lead.new
  end

  def create
    unless params[:email].blank?
      @lead = Lead.new(lead_params)
      @lead.save
    end

    redirect_to new_user_registration_path
  end

  private
    def lead_params
      params.require(:lead).permit(:email)
    end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController

  before_filter :authenticate_user!

  layout 'panel'

  def index
    @user = current_user

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  layout 'auth'

  # GET /resource/sign_up
  def new
    build_resource({})
    respond_with self.resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    if resource.save
      yield resource if block_given?
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          respond_with resource, :location => after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_afterp_sign_in!
          respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def after_sign_up_path_for(resource)
    case resource
      when User
        then root_path
      else
        root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MvpBaby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/auth.erb
<!DOCTYPE html>
<html>
<head>
  <title>MvpBaby</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render :partial => 'shared/analytics' if Rails.env.production? %>

</head>
<body>

  <div class="body">

    <div class="header background-header">
      <div class="header-left btn-blue">
        <% unless user_signed_in? %>
          <%= link_to('Página Inicial', leads_path) %>
        <% else %>
          <%= link_to('Painel de controle', panel_index_path)  %>
        <% end %>
      </div>

      <div class="header-rigth btn-blue">
        <%= render 'shared/auth' %>
      </div>
    </div>

    <div class="content background-context">
      <%= yield %>
    </div>

  </div>

</body>
</html>

app/views/layouts/panel.erb
<!DOCTYPE html>
<html>
<head>
  <title>MvpBaby</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="body">

    <div class="content background-context">

      <div class="menu-top">
        <%= render 'shared/menu_top' %>
      </div>

      <div class="menu-left" style="display: none;">
        <%= render 'shared/menu_left' %>
      </div>

      <%= yield %>
    </div>

  </div>

</body>
</html>

app/views/layouts/site.erb
<!DOCTYPE html>
<html>
<head>
  <title>MvpBaby</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:700,400' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="UTF-8">
  <meta name="description" content="Compartilhe e organize os passos do seu bebê, desde o enxoval, chá de bebê e até mesmo os primeiros aninhos, tudo em uma única ferramenta, em um lindo site personalizado.">
  <meta name="viewport" content="width=device-width">
  <meta property="og:url" content="https://desolate-falls-6899.herokuapp.com/"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Compartilhe e organize os passos do seu bebê."/>
  <meta property="og:site_name" content="Compartilhe e organize os passos do seu bebê." />
  <meta property="og:description" content="Compartilhe e organize os passos do seu bebê, desde o enxoval, chá de bebê e até mesmo os primeiros aninhos, tudo em uma única ferramenta, em um lindo site personalizado."/>

  <title>Compartilhe e organize os passos do seu bebê.</title>

  <%= render :partial => 'shared/analytics' if Rails.env.production? %>
</head>
<body>

  <div class="body background-img">
    <%= yield %>
  </div>

</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="land-message">
    <p>Compartilhe e organize os passos do seu bebê, desde o enxoval, chá de bebê e até mesmo os primeiros aninhos, tudo em uma única ferramenta, em um lindo site personalizado.</p>
  </div>

  <div class="land-lead">
    <%= f.text_field :email, class: "input-default input-lead", placeholder: "Informe seu email" %>
    <%= f.submit class: "btn-default btn-lead", value: "Experimentar grátis!" %>
  </div>

<% end %>

app/views/leads/index.html.erb
<section class="body">
  <%= render 'shared/auth' %>
  <%= render 'form' %>
</section>

app/views/panel/index.html.erb
Em breve :)

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49363224-2', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_auth.html.erb
<div class="form">
  <% if user_signed_in? %>
    <div class="form-edit">
      <%= link_to('Editar conta', edit_user_registration_path) %>
    </div>
  <% else %>
    <div class="form-register">
      <%= link_to('Cadastre-se', new_user_registration_path)  %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="form-logout">
      <%= link_to('Sair', destroy_user_session_path, :method => :delete) %>
    </div>
  <% else %>
    <div class="form-login">
      <%= link_to('Entrar', new_user_session_path)  %>
    </div>
  <% end %>
</div>

app/views/shared/_menu_left.html.erb
<ul>
  <li>
    <%= link_to panel_index_path, { title: "Painel de Controle" } do %>
      <i class="fa fa-tachometer fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Pais" } do %>
      <i class="fa fa-users fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Bebês" } do %>
      <i class="fa fa-child fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Planejamento" } do %>
      <i class="fa fa-calendar fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Fotos" } do %>
      <i class="fa fa-picture-o fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Vídeos" } do %>
      <i class="fa fa-video-camera fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Comunicação" } do %>
      <i class="fa fa-comment fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Redes sociais" } do %>
      <i class="fa fa-share-alt fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Segurança" } do %>
      <i class="fa fa-lock fa-2x"></i>
    <% end %>
  </li>

  <li>
    <%= link_to panel_index_path, { title: "Suporte" } do %>
      <i class="fa fa-question fa-2x"></i>
    <% end %>
  </li>

</ul>

app/views/shared/_menu_top.html.erb
<div class="navicon-left">
  <i class="fa fa-bars fa-2x"></i>
</div>

<div class="content-left">
  <input type="text" placeholder="O que você quer fazer? Exemplos: Criar uma nova página; Adicionar fotos;" list="actions-list"/>
  <datalist id="actions-list">
    <option>Painel de Controle</option>
    <option>Pai</option>
    <option>Mãe</option>
    <option>Padrinho</option>
    <option>Madrinha</option>
    <option>Bebê</option>
    <option>Planejamento</option>
    <option>Fotos</option>
    <option>Videos</option>
    <option>Redes sociais</option>
    <option>Comunicação</option>
    <option>Segurança</option>
    <option>Suporte</option>
  </datalist>
</div>

<div class="content-right">
  <ul>
    <li>
      <%= link_to panel_index_path, { title: "Visitar site" } do %>
        <i class="fa fa-link"></i>
      <% end %>
    </li>

    <li>
      <%= link_to panel_index_path, { title: "Notificações" } do %>
        <i class="fa fa-bell-o"></i>
      <% end %>
    </li>

    <li>
      <%= link_to panel_index_path, { title: "Configurações" } do %>
        <i class="fa fa-cog"></i>
      <% end %>
    </li>
  </ul>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>